const keyRows = [
  [
    { className: "pinky", id: "ESCAPE", label: "ESC" },
    { className: "pinky", id: "DIGIT1", label: "1" },
    { className: "ring", id: "DIGIT2", label: "2" },
    { className: "middle", id: "DIGIT3", label: "3" },
    { className: "pointer1st", id: "DIGIT4", label: "4" },
    { className: "pointer2nd", id: "DIGIT5", label: "5" },
    { className: "pointer2nd", id: "DIGIT6", label: "6" },
    { className: "pointer1st", id: "DIGIT7", label: "7" },
    { className: "middle", id: "DIGIT8", label: "8" },
    { className: "ring", id: "DIGIT9", label: "9" },
    { className: "pinky", id: "DIGIT0", label: "0" },
    { className: "pinky", label: "-" },
    { className: "pinky", label: "+" },
    { className: "pinky", id: "BACKSPACE", label: "BACK" },
  ],
  [
    { className: "pinky", id: "TAB", label: "TAB" },
    { className: "pinky", id: "KEYQ", label: "Q" },
    { className: "ring", id: "KEYW", label: "W" },
    { className: "middle", id: "KEYE", label: "E" },
    { className: "pointer1st", id: "KEYR", label: "R" },
    { className: "pointer2nd", id: "KEYT", label: "T" },
    { className: "pointer2nd", id: "KEYY", label: "Y" },
    { className: "pointer1st", id: "KEYU", label: "U" },
    { className: "middle", id: "KEYI", label: "I" },
    { className: "ring", id: "KEYO", label: "O" },
    { className: "pinky", id: "KEYP", label: "P" },
    { className: "pinky", label: "[" },
    { className: "pinky", label: "]" },
    { className: "pinky", label: "\\" },
  ],
  [
    { className: "pinky", id: "CAPSLOCK", label: "CAPS" },
    { className: "pinky", id: "KEYA", label: "A" },
    { className: "ring", id: "KEYS", label: "S" },
    { className: "middle", id: "KEYD", label: "D" },
    { className: "pointer1st", id: "KEYF", label: "F" },
    { className: "pointer2nd", id: "KEYG", label: "G" },
    { className: "pointer2nd", id: "KEYH", label: "H" },
    { className: "pointer1st", id: "KEYJ", label: "J" },
    { className: "middle", id: "KEYK", label: "K" },
    { className: "ring", id: "KEYL", label: "L" },
    { className: "pinky", label: ":" },
    { className: "pinky", label: "''" },
    { className: "pinky", id: "ENTER", label: "ENTER" },
  ],
  [
    { className: "pinky", id: "SHIFTLEFT", label: "SHIFT" },
    { className: "pinky", id: "KEYZ", label: "Z" },
    { className: "ring", id: "KEYX", label: "X" },
    { className: "middle", id: "KEYC", label: "C" },
    { className: "pointer1st", id: "KEYV", label: "V" },
    { className: "pointer2nd", id: "KEYB", label: "B" },
    { className: "pointer2nd", id: "KEYN", label: "N" },
    { className: "pointer1st", id: "KEYM", label: "M" },
    { className: "middle", label: "," },
    { className: "ring", label: "." },
    { className: "pinky", label: ";" },
    { className: "pinky", id: "SHIFTRIGHT", label: "SHIFT" },
  ],
  [
    { className: "pinky", id: "CONTROLLEFT", label: "Ctrl" },
    { className: "pinky", id: "ALTLEFT", label: "Alt" },
    { className: "thumb", id: "SPACE", label: "Space" },
    { className: "pinky", id: "ALTRIGHT", label: "Alt" },
    { className: "pinky", id: "CONTROLRIGHT", label: "Ctrl" },
  ]
];

export default keyRows;

