const keyRows = [
    [
      { className: "pinky", id: "esc", label: "ESC" },
      { className: "pinky", id: "1", label: "1" },
      { className: "ring", id: "2", label: "2" },
      { className: "middle", id: "3", label: "3" },
      { className: "pointer1st", id: "4", label: "4" },
      { className: "pointer2nd", id: "5", label: "5" },
      { className: "pointer2nd", id: "6", label: "6" },
      { className: "pointer1st", id: "7", label: "7" },
      { className: "middle", id: "8", label: "8" },
      { className: "ring", id: "9", label: "9" },
      { className: "pinky", id: "10", label: "0" },
      { className: "pinky", label: "-" },
      { className: "pinky", label: "+" },
      { className: "pinky", id: "back", label: "BACK" },
    ],
    [
      { className: "pinky", id: "tab", label: "TAB" },
      { className: "pinky", id: "Q", label: "Q" },
      { className: "ring", id: "W", label: "W" },
      { className: "middle", id: "E", label: "E" },
      { className: "pointer1st", id: "R", label: "R" },
      { className: "pointer2nd", id: "T", label: "T" },
      { className: "pointer2nd", id: "Y", label: "Y" },
      { className: "pointer1st", id: "U", label: "U" },
      { className: "middle", id: "I", label: "I" },
      { className: "ring", id: "O", label: "O" },
      { className: "pinky", id: "P", label: "P" },
      { className: "pinky", label: "[" },
      { className: "pinky", label: "]" },
      { className: "pinky", label: "\\" },
    ],
    [
      { className: "pinky", id: "caps", label: "CAPS" },
      { className: "pinky", id: "A", label: "A" },
      { className: "ring", id: "S", label: "S" },
      { className: "middle", id: "D", label: "D" },
      { className: "pointer1st", id: "F", label: "F" },
      { className: "pointer2nd", id: "G", label: "G" },
      { className: "pointer2nd", id: "H", label: "H" },
      { className: "pointer1st", id: "J", label: "J" },
      { className: "middle", id: "K", label: "K" },
      { className: "ring", id: "L", label: "L" },
      { className: "pinky", label: ":" },
      { className: "pinky", label: "''" },
      { className: "pinky", id: "enter", label: "ENTER" },
    ],
    [
      { className: "pinky", id: "left-shift", label: "SHIFT" },
      { className: "pinky", id: "Z", label: "Z" },
      { className: "ring", id: "X", label: "X" },
      { className: "middle", id: "C", label: "C" },
      { className: "pointer1st", id: "V", label: "V" },
      { className: "pointer2nd", id: "B", label: "B" },
      { className: "pointer2nd", id: "N", label: "N" },
      { className: "pointer1st", id: "M", label: "M" },
      { className: "middle", label: "," },
      { className: "ring", label: "." },
      { className: "pinky", label: ";" },
      { className: "pinky", id: "right-shift", label: "SHIFT" },
    ],
    [
      { className: "pinky", id: "left-ctrl", label: "Ctrl" },
      { className: "pinky", id: "left-alt", label: "Alt" },
      { className: "thumb", id: "spacebar", label: "Space" },
      { className: "pinky", id: "right-alt", label: "Alt" },
      { className: "pinky", id: "right-ctrl", label: "Ctrl" },
    ]
    
  ]

  export default keyRows;